"""empty message

Revision ID: 29a5dcaaa2f4
Revises: 
Create Date: 2022-03-25 11:25:24.251205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a5dcaaa2f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ate', sa.Unicode(length=255), nullable=True),
    sa.Column('amount', sa.Unicode(length=255), nullable=True),
    sa.Column('ate_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jcode', sa.VARCHAR(), nullable=True),
    sa.Column('temp', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('books')
    # ### end Alembic commands ###
